---
title: "Parliament Dot Plots"
author: "Zoe Meers"
date: "22/05/2018"
output: pdf_document:
    toc:TRUE
    toc_depth:4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("westminster.R")
source("scale_colours_parties.R")
source("geom_parliament_dots.R")
library(ggparliament)
```

# Unique parliament layouts

## Westminster Parliaments

### United Kingdom

#### Load data
```{r}
ukresults <- read_csv("UK2017.csv")
ukresults <- ukresults %>%
    filter(!is.na(win)) %>%
    group_by(win) %>%
    count(win) 
ukresults$n <- as.numeric(ukresults$n)
left_parties <- c("lab","snp","lib","grn","plc", "ind","oth")
ukresults$location <-
  ifelse(ukresults$win %in% left_parties, "left",
         ifelse(ukresults$win==c("con"), "right",
                ifelse(ukresults$win==c("dup"), "crossbench",
                        NA  )))
ukresults_left <- ukresults %>%
  filter(location=="left")
ukresults_right <- ukresults %>%
  filter(location=="right")

```

#### Plot 
```{r}
leftside <- ggplot_westminster(dat = ukresults_left, seatspp = ukresults_left$n, partyvar = ukresults_left$n, rows = 10)

rightside <- ggplot_westminster(dat = ukresults_right, seatspp = ukresults_right$n, partyvar = ukresults_right$n, rows = 10)

combine_westminster(left = leftside, right = rightside)
```


## Hemicycle
### EU, France, United States, and so on...

#### Load data...
```{r}
americandata <- data(US_congress)
americandata <- US_congress
US_congress1 <- americandata %>%
  filter(start_year=="2017" & chamber=="lower")
US_senate <- americandata %>%
  filter(start_year=="2017" & chamber=="upper")
```

#### Plot
```{r}
congress <- ggplot() + geom_parliament_dots(type='hemicycle', totalseats=sum(US_congress1$seats), parlrows=10, seatspp=US_congress1$seats) + theme_void() + labs(colour="Party", title="United States Congress") + scale_colour_manual(values=c("blue", "red"), labels=c("D", "R"))

senate <- ggplot() + geom_parliament_dots(type='hemicycle', totalseats=sum(US_senate$seats), parlrows=3, seatspp=US_senate$seats) + theme_void() + labs(colour="Party", title="United States Senate") + scale_colour_manual(values=c("blue", "red", "gray"), labels=c("D", "R", "I"))
senate
congress
```


## U-Shape parliament
### Australia, New Zealand
