---
title: "Parliament Dot Plots"
author: "Zoe Meers"
date: "22/05/2018"
output:
  html_document:
    toc: yes
    toc_depth: 4
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
source("geom_parliament_dots.R")
source("scale_colours_parties.R")
load("election_data.rda")
library(ggparliament)
library(tidyverse)
#library(patchwork)
```

# Unique parliament layouts:

Monkey Cage article : https://www.washingtonpost.com/news/monkey-cage/wp/2017/03/04/these-5-designs-influence-every-legislature-in-the-world-and-tell-you-how-each-governs/?utm_term=.e1e1c1c3c37b

## Opposing benches parliament

### United Kingdom, Canada

#### Data
```{r}
ukresults <- election_data %>%
  filter(country=="UK" & year == 2017) 
ukresults$seats <- as.numeric(ukresults$seats)
left_parties <- c("Labour","Scottish National Party","Liberal Democrats","Green","Plaid Cymru", "Ind")
right_parties <- c("Conservative", "Democratic Unionist")
ukresults$location <-
  ifelse(ukresults$party_long %in% left_parties, "left",
         ifelse(ukresults$party_long %in% right_parties, "right",
                        NA  ))
ukresults_left <- ukresults %>%
  filter(location=="left")

ukresults_right <- ukresults %>%
  filter(location=="right")

```

#### Plot 
```{r}
leftside <- ggplot() + geom_parliament_dots(type="opposing_benches", seatspp = ukresults_left$seats, size = 3, party_name = ukresults_left$party_long, parlrows=10) + theme_parliament() + coord_flip()  + theme(legend.position="left") + labs(colour="", title="Opposing benches parliament: Westminster") + scale_colour_manual(values=c(ukresults_left$colour), labels=c(ukresults_left$party_long),limits=c(ukresults_left$party_long))

rightside <- ggplot() + geom_parliament_dots(type="opposing_benches", seatspp = ukresults_right$seats, size = 3, party_name = ukresults_right$party_long, parlrows=10)+ theme_parliament() + coord_flip()  + labs(colour="") + scale_colour_manual(values=c( ukresults_right$colour), labels=c(ukresults_right$party_long), limits=c(ukresults_right$party_long))

uk_parliament <- combine_opposingbenches(left = leftside, right = rightside)
uk_parliament 
```


## Semicircle parliament
### EU, France, United States, and so on...

#### Data
```{r}
americandata <- data(US_congress)
americandata <- US_congress
US_congress1 <- americandata %>%
  filter(start_year=="2017" & chamber=="lower")
US_senate <- americandata %>%
  filter(start_year=="2017" & chamber=="upper")
```

#### Plot
```{r}
congress <- ggplot() + geom_parliament_dots(type='semicircle', totalseats=sum(US_congress1$seats), parlrows=10, size=3, seatspp=US_congress1$seats) + theme_parliament() + labs(colour="Party", title="United States Congress") + scale_colour_manual(values=c("#1c396e", "#ed1b35"), labels=c("D", "R")) 
#When I write scale_colour_party, Republicans show up as grey. Trying to fix it but in the meantime, there is a manual scale.
#It works below, however. :\
senate <- ggplot() + geom_parliament_dots(type='semicircle', totalseats=sum(US_senate$seats), parlrows=3, size=3, seatspp=US_senate$seats) + theme_parliament() + labs(colour="Party", title="United States Senate") +  scale_colour_party(palette="USA", labels=c("D", "R", "I"))
senate
congress
```


## Horseshoe parliament
### Australia, New Zealand


#### Data
```{r}
# load data
AustralianElections <- pscl::AustralianElections
# filter to 2016, slice percent, total seats
AustralianElections <- AustralianElections %>%
  filter(date == "2016-07-02") %>%
  gather() %>%
  slice(-c(1:3, 8:19))

# reorder rows into parliament layout (i.e. independents in the middle of the circle btwn the two major parties)
AustralianElections <- AustralianElections[c(1, 4, 3, 2), ]
AustralianElections$key <- factor(AustralianElections$key)
# clean labels
AustralianElections$key <- gsub("Seats", "", AustralianElections$key)
au <- AustralianElections
new_au_data <- parliament_data(data=au, seats=au$value, type='horseshoe')



au_elections <- election_data %>%
  filter(year==2016 & country=="Australia" & house=="Representatives")
#new_au_data <- parliament_data(data=au_elections, seats=au_elections$seats, type='horseshoe')
```


#### Plot
```{r}
a <- ggplot() + geom_parliament_dots(type='horseshoe', totalseats=sum(new_au_data$value), parlrows = 4, size=3, seatspp=new_au_data$value) + theme_parliament() +  labs(colour="Party", title="Horseshoe parliament: Australia") + scale_colour_party(palette="AUS", labels=c("ALP","Ind.","NP", "LP"))
a  
```

## Circle parliament

### old German Bundestag (find more modern examples).

```{r}
russia <- election_data %>%
  filter(country=="Russia" & year==2016)

ggplot() + geom_parliament_dots(type="circle", seatspp = russia$seats, size = 3, party_name = russia$party_long, parlrows=10)+ theme_parliament() + coord_polar() + scale_y_discrete(expand=c(1, 0)) + 
  scale_colour_manual(values=c(russia$colour), labels=c(russia$party_long), limits=c(russia$party_long)) + labs(colour='', title="Russian Parliament")
```

## Classroom parliament

### China, Russia, North Korea

```{r}

ggplot() + geom_parliament_dots(type="classroom", seatspp = russia$seats, size = 3, party_name = russia$party_long, parlrows=15) + theme_parliament() +
  scale_colour_manual(values=c(russia$colour), labels=c(russia$party_long), limits=c(russia$party_long)) + labs(colour='', title="Russian Parliament") 
```





